stages:
  - build
  - deploy

variables:
  SERVICE: $CI_PROJECT_NAME
  VERSION: $CI_COMMIT_TAG
  DOCKER_BUILDKIT: 1
  DOMEN: dev.merlines.ru
  
  KUBE_NAMESPACE: develop

include:
  - project: 'merlines/ci-cd'
    ref: develop
    file:
      # - 'test.yml'
      - 'build.yml'
      - 'deploy.yml'
