{{- if .Values.stripPrefix.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Chart.Name }}-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.stripPrefix.path }}
{{- end }}
